### ISSUE TITLE
Facebook and Twitter login functionality

### ISSUE THREAD

**Issue by Engineering-Robert** [vinitkumar/node-twitter#122]
I see there is some code related to retrieving information from Facebook and Twitter. I think it might be for user authentication purposes, but i'm not sure (haven't looked into it at all). I'm wondering if all the Facebook & Twitter code can be removed since it appears as though the only login method that shows up on the login screen is for Github.

@vinitkumar let me know about this.

**Comment by vinitkumar** [comment]
@Engineering-Robert Historically, we used to have login with fb and twitter, I removed it because the user info was slightly different in them and we had to account for all/missing details.

For eg: a user from github will have followers but user from facebook won't have it. 
So, you definitely remove the code from twitter and facebook.

**Comment by Engineering-Robert** [comment]
Ok, great, thanks for clarifying!
