### ISSUE TITLE
Error: secret option required for sessions

### ISSUE THREAD

**Issue by jahidmixmaster** [vinitkumar/node-twitter#235]
After running the application, I got an error "Error: secret option required for sessions"

**Screenshots**
![node_writter](https://user-images.githubusercontent.com/25489992/54242203-0c5be900-4524-11e9-8430-36ee834312e0.JPG)

**Solved**
 - set cookieParser in config/express.js file 
 - app.use(cookieParser("secret"));

**Comment by vinitkumar** [comment]
@jahidmixmaster Well, the issue is that you have not set secret as environment variable before running the server. The secret should never be stored in the code but set as environment variable.

Here in the code, the secret is set from environment:

```js
app.use(
    session({
      secret: process.env.SECRET,
      resave: false,
      saveUninitialized: false,
      store: new mongoStore({
        url: config.db,
        collection: "sessions"
      })
    })
  );
```

Here is the link for the relevant line of code.

https://github.com/vinitkumar/node-twitter/blob/f4adf572e11ed1fe5733102deb299657f848232b/config/express.js#L78

Set this environment variable and you should be good to go :)

Cheers ☕️

**Comment by jahidmixmaster** [comment]
yes. Btw thanks for your wonderful job.

**Comment by vinitkumar** [comment]
@jahidmixmaster You are welcome. I still have some improvements planned for it but can't find time it being a side project and all. 

Please feel free to contribute to the project. 
It could be code, documentation, wiki or logo as well. I would love to see what you contribute.
